/*

	define arrays for convoys

	[[waypointpositions], [classname, position, spawndirection]], // (convoyID 0)
	[[waypointpositions], [classname, position, spawndirection]] // (convoyID 1)
	etc

*/



[
	[
		[
			"convoyEast_wp_1",
			"convoyEast_wp_2",
			"convoyEast_wp_3",
			"convoyEast_wp_4",
			"convoyEast_wp_5",
			"convoyEast_wp_6",
			"convoyEast_wp_7"
		],
		[
			"convoyEast_pos_1",
			"convoyEast_pos_2",
			"convoyEast_pos_3",
			"convoyEast_pos_4",
			"convoyEast_pos_5",
			"convoyEast_pos_6",
			"convoyEast_pos_7",
			"convoyEast_pos_8",
			"convoyEast_pos_9"
		],
		[
			"gm_gc_army_brdm2",
		    "gm_gc_army_ural4320_cargo",
		    "gm_gc_army_ural4320_cargo",					
		    "gm_gc_army_ural4320_cargo",
		    "gm_gc_army_ural4320_reammo",
		    "gm_gc_army_ural4320_repair",
		    "gm_gc_army_ural375d_refuel",
		    "gm_gc_army_ural375d_refuel",
		    "gm_gc_army_btr60pb"
		]
	],
	[
		[
			"convoyNorth_wp_1",
			"convoyNorth_wp_2",
			"convoyNorth_wp_3",
			"convoyNorth_wp_4",
			"convoyNorth_wp_5",
			"convoyNorth_wp_6",
			"convoyNorth_wp_7",
			"convoyNorth_wp_8",
			"convoyNorth_wp_9",
			"convoyNorth_wp_10",
			"convoyNorth_wp_11",
			"convoyNorth_wp_12",
			"convoyNorth_wp_13",
			"convoyNorth_wp_14",
			"convoyNorth_wp_15",
			"convoyNorth_wp_16",
			"convoyNorth_wp_17",
			"convoyNorth_wp_18",
			"convoyNorth_wp_19",
			"convoyNorth_wp_20",
			"convoyNorth_wp_21",
			"convoyNorth_wp_22",
			"convoyNorth_wp_23",
			"convoyNorth_wp_24",
			"convoyNorth_wp_25",
			"convoyNorth_wp_26",
			"convoyNorth_wp_27",
			"convoyNorth_wp_28",
			"convoyNorth_wp_29",
			"convoyNorth_wp_30",
			"convoyNorth_wp_31",
			"convoyNorth_wp_32",
			"convoyNorth_wp_33",
			"convoyNorth_wp_34",
			"convoyNorth_wp_35",
			"convoyNorth_wp_36",
			"convoyNorth_wp_37",
			"convoyNorth_wp_38",
			"convoyNorth_wp_39",
			"convoyNorth_wp_40",
			"convoyNorth_wp_41",
			"convoyNorth_wp_42",
			"convoyNorth_wp_43",
			"convoyNorth_wp_44",
			"convoyNorth_wp_45",
			"convoyNorth_wp_46",
			"convoyNorth_wp_47",
			"convoyNorth_wp_48",
			"convoyNorth_wp_49",
			"convoyNorth_wp_50",
			"convoyNorth_wp_51",
			"convoyNorth_wp_52",
			"convoyNorth_wp_53",
			"convoyNorth_wp_54",
			"convoyNorth_wp_55",
			"convoyNorth_wp_56",
			"convoyNorth_wp_57",
			"convoyNorth_wp_58",
			"convoyNorth_wp_59",
			"convoyNorth_wp_60",
			"convoyNorth_wp_61",
			"convoyNorth_wp_62"
		],
		[
			"convoyNorth_pos_1",
			"convoyNorth_pos_2",
			"convoyNorth_pos_3",
			"convoyNorth_pos_4",
			"convoyNorth_pos_5",
			"convoyNorth_pos_6",
			"convoyNorth_pos_7",
			"convoyNorth_pos_8",
			"convoyNorth_pos_9"
		],
		[
			"gm_gc_army_brdm2",
		    "gm_gc_army_ural4320_cargo",
		    "gm_gc_army_ural4320_cargo",					
		    "gm_gc_army_ural4320_cargo",
		    "gm_gc_army_ural4320_reammo",
		    "gm_gc_army_ural4320_repair",
		    "gm_gc_army_ural375d_refuel",
		    "gm_gc_army_ural375d_refuel",
		    "gm_gc_army_btr60pb"
		]
	]
]